### ISSUE TITLE
Kanban board set up

### ISSUE THREAD

**Issue by MarcoDDM** [MarcoDDM/recipeapp#11]
This is the Kanban board that we build with @Felipe-Perez-Ferraro 

https://github.com/users/MarcoDDM/projects/3/views/1

In this issue we:
- Assigned tasks
- Organize workflow

Thank you for your time. If you have any doubt, don't hesitate to tag me or my coding partner.

**Comment by brainconnect93** [comment]
### Hi @gersonhiggins & @danifromecuador, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/kghYzGafFW0AAAAM/almost-paul-walker.gif">

## Good Points 👍

- Task properly assigned ✔️
- Kanban board created ✔️
- Descriptive issues summary✔️


### Changes Required

- You have done great so far 👍 However, there are a few requirements you still need to meet.

- [ ] You did great sharing the task with each student, but just as you have done before in your previous group project, the columns in your kanban board are missing the `In Review` column as this column will serve as a space where your project will be moved when reviewing each other's pull request before the final submission. I would kindly suggest you add the `In Review` column in between the `In Progress` and `Done` column.

![review](https://github.com/MarcoDDM/recipe/assets/78634841/1a034304-126c-4b38-89d5-e9e70c7f50fb)

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by V-Blaze** [comment]
Hi @MarcoDDM, @Felipe-Perez-Ferraro  

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Kanban board setup correctly💯
-  All tasks are assigned 👍
-  Descriptive summary  🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
